# Generated by Django 5.1.3 on 2025-05-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(to="blogapp.tag"),
        ),
    ]
